version: "3.1"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_USER: calculus
            POSTGRES_DB: calculus
        networks:
            - calculus
        volumes: 
            - ./data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    ms:
        build: .
        restart: always
        networks:
            - calculus
        depends_on:
            - db
networks:
  calculus:
    driver: bridge
